# Generated by Django 2.1.7 on 2025-06-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_wavelet', '0002_predictionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='cwt_image_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
