# Generated by Django 2.1.7 on 2025-06-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_wavelet', '0003_predictionhistory_cwt_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
