# Generated by Django 2.1.7 on 2025-06-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_wavelet', '0004_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
